### ISSUE TITLE
Installaiton problems

### ISSUE THREAD

**Issue by LiXiang0021** [TuSimple/RangeDet#19]
Thanks for writer's excellent work!
When i try to install as the instruction at the aim file, i got these errors.
`pip install -v -e .`

CMake Error at CMakeLists.txt:14 (find_package):
      By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "pybind11",
      but CMake did not find one.
      Could not find a package configuration file provided by "pybind11" with any
      of the following names:

        pybind11Config.cmake
        pybind11-config.cmake

      Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
      "pybind11_DIR" to a directory containing one of the above files.  If
      "pybind11" provides a separate development package or SDK, be sure it has
      been installed.
`

Can anyone help me? 
Thanks a lot!

**Comment by LiXiang0021** [comment]
I had alerday handled the above problem. But, I got another one: shown as below.


Traceback (most recent call last):
  File "/home/lijianguo/test_files/RangeDet/tools/train.py", line 2, in <module>
    _=ctypes.CDLL('./operator_cxx/contrib/contrib_cxx.so')
  File "/home/lijianguo/anaconda3/envs/salsa_t/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./operator_cxx/contrib/contrib_cxx.so: cannot open shared object file: No such file or directory

Did anyone met this? 
Thanks for your response.

**Comment by BAI-Yeqi** [comment]
@LiXiang0021 

Hi, seems instructions under this issue will solve your problem: [Issue-6](https://github.com/tusen-ai/RangeDet/issues/6)

**Comment by Maomao-Ran** [comment]
pip install pybind11[global]  solves this problem pybind11Config.cmake
